import { unresolved, verifiedCount, observationResolved } from './data.js';
export const prompts = ['Why is this property flagged?', 'What should I do first?', 'Create a four-week mitigation plan.', 'What evidence is still missing?', 'What changed after the work?', 'Will this lower my insurance premium?'];
export function answer(question, p) {
  const q = question.toLowerCase();
  if (/premium|insurance|discount|coverage/.test(q)) return { text: 'Documented mitigation may support an insurer’s review. Your insurer determines whether the evidence is accepted and whether pricing, eligibility or coverage changes. TerraShield cannot guarantee a discount.', action: 'evidence', label: 'Review evidence' };
  if (/budget|cost|price|quote|afford/.test(q)) return { text: 'This demo contains no contractor estimates. Clearing accessible stored items may be owner-manageable; vegetation work may need a contractor quote, and site or construction assessments may need a qualified professional. Enter a planning budget and obtain estimates before committing to work.', action: 'plan', label: 'Open budget & action plan' };
  if (/four.week|4.week|schedule/.test(q)) return { text: 'Draft four-week template: Week 1 — document baseline conditions and obtain advice. Week 2 — clear accessible stored items and agree vegetation work. Week 3 — finish planned work and capture matching evidence. Week 4 — submit documentation and review gaps. This is a planning template; timing depends on access, advice, and estimates.', action: 'apply-schedule', label: 'Apply to action plan' };
  if (/first|priorit|what should|recommend/.test(q)) {
    const next = unresolved(p).filter(a => a.priority === 'High');
    return { text: next.length ? `For ${p.name}, start with ${next.map(a => a.title.toLowerCase()).join(' and ')}. These priorities follow the sample property observations. Capture baseline photos first and seek qualified advice for work beyond your capabilities. Owner completion still requires evidence review.` : `For ${p.name}, focus next on ${unresolved(p).map(a => a.title.toLowerCase()).join(' and ')}. Previously reviewed changes do not resolve these evidence gaps.`, action: 'plan', label: 'Open prioritized actions', extra: next[0] ? { action: `add-${next[0].id}`, label: 'Add first action to plan' } : null };
  }
  if (/missing|gap|unresolved|outstanding/.test(q)) return { text: `Still needed for ${p.name}: ${unresolved(p).map(a => `${a.title}: ${a.required}`).join(' ')} Roof and vent details cannot be established from aerial imagery.`, action: 'evidence', label: 'Open evidence checklist' };
  if (/changed|after|reduc|score/.test(q)) return verifiedCount(p) ? { text: 'Prepared sample evidence confirms changed near-building vegetation and removal of stored combustible items. Oakridge’s illustrative index changed from 82 to 58 — a 24-point index change, not a reduction in fire probability or insured losses. Wider vegetation assessment and roof/vent specifications remain unresolved.', action: 'report', label: 'Open mitigation report' } : { text: `No changes have been verified for ${p.name}. The current illustrative score is ${p.score}/100. Uploading a file or marking work in progress does not change the modeled score. A prepared review scenario is available for Oakridge House.`, action: 'evidence', label: 'Open evidence' };
  if (/flag|why|observ|risk|expos/.test(q)) return { text: `${p.name} has these baseline observations from August 15, 2026: ${p.observations.map(o => `${o.title} (${o.source}; ${observationResolved(p,o) ? 'addressed in prepared September 15 evidence, verified in demo' : o.status.toLowerCase()})`).join('. ')}. ${verifiedCount(p) ? 'Remaining concern includes surrounding vegetation and unresolved evidence gaps. ' : ''}Roof and vent specifications remain unverified. The index is illustrative, not a fire probability.`, action: 'evidence', label: 'View referenced evidence', refs: p.observations.map(o => ({ action: o.action, label: o.title })) };
  return { text: 'This demo does not contain enough information to answer that question. I can explain the selected property’s observations, help organize a mitigation plan, identify missing evidence, or explain the sample review result.', action: 'plan', label: 'Explore action plan' };
}
