import { unresolved, verifiedCount, evidenceCoverage, exposureCategory } from './data.js';

export const prompts = ['Why is this property flagged?', 'What should I do first?', 'Create a four-week mitigation plan.', 'What evidence is still missing?', 'What changed after the work?', 'Is my house safe now?', 'Will this lower my insurance premium?'];

export function answer(question, p) {
  const q = question.toLowerCase(), coverage = evidenceCoverage(p), verified = verifiedCount(p);
  if (/safe/.test(q)) return { text: `${verified} actions have been verified in this demo, but this does not establish that ${p.name} is safe. Surrounding wildfire exposure remains ${exposureCategory(p).toLowerCase()}, and ${coverage.outstanding.join(' and ').toLowerCase()} remain outstanding.`, action: 'evidence', label: 'Open verification' };
  if (/fall|reduc|score|how much/.test(q)) return { text: 'This prototype does not quantify a validated reduction in fire probability or financial loss. It shows which observable conditions changed and which actions were verified.', action: 'updated-risk', label: 'See assessment after review' };
  if (/premium|insurance|discount|coverage/.test(q)) return { text: 'The report documents completed actions, but your insurer decides whether it accepts evidence and whether any pricing or coverage changes apply.', action: 'report', label: 'Open assessment report' };
  if (/four.week|4.week|schedule/.test(q)) return { text: 'Draft four-week template: document baseline conditions and obtain advice; address agreed accessible work; complete planned work and capture matching evidence; then submit documentation and review gaps. This is a planning template, not a completion guarantee.', action: 'apply-schedule', label: 'Apply to recommendation' };
  if (/missing|gap|outstanding/.test(q)) return { text: `Evidence coverage is ${coverage.label.toLowerCase()} for ${coverage.scope.toLowerCase()}. Still needed: ${coverage.outstanding.join('; ')}. Roof and vent details need documentation or qualified inspection.`, action: 'evidence', label: 'Open verification' };
  if (/first|priorit|recommend/.test(q)) { const next = unresolved(p).filter(a => a.priority === 'High'); return { text: `Start with ${next.map(a => a.title.toLowerCase()).join(' and ')}. These are illustrative recommendations based on documented observations, not actuarial weights.`, action: 'plan', label: 'Open recommendation' }; }
  if (/changed|after/.test(q)) return { text: verified ? `Prepared evidence confirms two observable changes. ${verified} of ${p.actions.length} actions are verified in demo. Surrounding exposure remains ${exposureCategory(p).toLowerCase()}, and unresolved assessment items remain.` : 'No changes have been verified. Uploading a file alone does not verify work or change surrounding exposure.', action: 'evidence', label: 'Open verification' };
  if (/flag|why|observ|risk|expos/.test(q)) return { text: `Surrounding wildfire exposure is ${exposureCategory(p).toLowerCase()} in this illustrative demo. Property findings are separate: ${p.observations.map(o => `${o.title} (${o.findingStatus})`).join('; ')}. Exposure describes surrounding conditions, not building resistance.`, action: 'overview', label: 'Read assessment' };
  return { text: 'This demo can explain surrounding exposure, observed property vulnerabilities, mitigation progress, evidence coverage, and next steps. It does not estimate a calibrated probability of fire or financial loss.', action: 'overview', label: 'Read assessment' };
}
